version: '3'

services:
  db:
    restart: always
    image: mysql:5.7.18
    container_name: db_mysql
    volumes:
      - /Users/liujianhui/apps/awesome/packages/nest-app/mysql/mydir:/mydir
      - /Users/liujianhui/apps/awesome/packages/nest-app/mysql/datadir:/var/lib/mysql
      - /Users/liujianhui/apps/awesome/packages/nest-app/mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - /Users/liujianhui/apps/awesome/packages/nest-app/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=db"
      - "TZ=Asia/Shanghai"
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 33061:3306